apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: static-v4-decorator
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 1
  ingresses:
    - "https://static-v4-decorator.nais.preprod.local"
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 64Mi

