apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: static-v4-decorator
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://static-v4-decorator.nais.adeo.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi

